name: Build Documentation

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  build-documentation:
    name: Build and deploy cFS documents
    uses: jphickey/cFS/.github/workflows/build-doc-reusable.yml@jph-wip-cfs1097-doc-workflow
    with:
      target: "[\"fm-usersguide\"]"
      app-name: fm
      buildpdf: ${{ github.event_name == 'push' && (contains(github.ref, 'main') || contains(github.ref, 'dev')) }}
